@echo off
cd "C:\Users\RanchDB\Desktop\RanchDB\Livestock-Mobile"

echo Pulling latest code...
git pull origin main
echo Installing dependencies...
call npm install
echo Building production frontend...
call npm run build
echo Restarting PM2 applications...
call pm2 delete all
call pm2 start ecosystem.prod.config.js
call pm2 save
echo Verifying deployment...
call pm2 status